version: '3.0'
services:
  mytb:
    restart: always
    image: 'thingsboard/tb-postgres'
    ports:
      - '8080:9090'
      - '1883:1883'
      - '7070:7070'
      - '5683-5688:5683-5688/udp'
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard

  m9-bridge:
    restart: always
    image: m9-bridge
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - MQTT_SINK_URL=mqtt://mytb:1883
